// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.scss";
import Modal from "@/components/Modal/Modal";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body 
      // className={`${geistSans.variable} ${geistMono.variable}`}
      >
        {children}
        {/* Đặt Modal ở đây để nó luôn hiển thị, khi isOpen là true */}
        <Modal />
      </body>
    </html>
  );
}
